
name: Aqua Billy

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  aqua:
    runs-on: ubuntu-latest

    steps:
      - name: Build and push
        uses: tamirsinai/shared-workflows/billy@main