name: Aqua Trivy

on:
  pull_request:

jobs:
  aqua:
    runs-on: ubuntu-latest

    steps:
      - name: Aqua scanner
        uses: public-sami-org-1/shared-workflows/.github/workflows/aqua.yml@main
